name: Deploy
on:
  push:	
    branches:	
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  deploy:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: Install Requirments 
      run: pip install -r requirements.txt
    - name: run example to get the html file
      run: python example.py
    - run: mkdir result
    - run: mv index.html result
    - name: Deploy to github
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:murez/google-scholar-export.git
        BRANCH: result
        FOLDER: result
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
